PacketIntranet/Controllers/Products/OriginManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PacketIntranet.Models;
using PacketIntranet.Models.ProductModel;

namespace PacketIntranet.Controllers.Products
{ 
    public class OriginManagerController : Controller
    {
        private MvcApplicationDBEntities db = new MvcApplicationDBEntities();

        //
        // GET: /ProductTypesManager/

        public ViewResult Index()
        {
            OriginModel model = new OriginModel()
            {
                List_tbl_Origins = db.tbl_Origins.ToList(),
            };
            return View(model);
        }

        //
        // GET: /ProductTypesManager/Details/5

        public ViewResult Details(int id)
        {
            tbl_Origins tbl_Origins = db.tbl_Origins.Single(t => t.Ori_Id == id);
            return View(tbl_Origins);
        }

        //
        // GET: /ProductTypesManager/Create

        public ActionResult Create()
        {

            OriginModel model = new OriginModel()
            {
                One_tbl_Origins = new tbl_Origins()
            };
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(OriginModel tbl_Origins)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Origins.AddObject(tbl_Origins.One_tbl_Origins);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Origins);
        }

        //
        // GET: /ProductTypesManager/Edit/5

        public ActionResult Edit(int id)
        {
            OriginModel model = new OriginModel()
            {
                One_tbl_Origins = db.tbl_Origins.Single(t => t.Ori_Id == id),
            };
            // tbl_Origins tbl_Origins = db.tbl_Origins.Single(t => t.Ori_Id == id);
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(OriginModel tbl_Origins, int id)
        {
            if (ModelState.IsValid)
            {
                var Update_Origin = db.tbl_Origins.Single(a => a.Ori_Id == id);
                Update_Origin.Ori_Conutry = tbl_Origins.One_tbl_Origins.Ori_Conutry;
                Update_Origin.Descriptions = tbl_Origins.One_tbl_Origins.Descriptions;

                UpdateModel(Update_Origin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Origins);
        }



        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(FormCollection Collection)
        {
            string All_IdProductType = Collection.Get("GetAll_Id");
            foreach (var item in All_IdProductType.Split(','))
            {

                if (item.ToString() != "000")
                {
                    int ConvertId = Convert.ToInt32(item);
                    tbl_Origins tbl_Origins = db.tbl_Origins.Single(t => t.Ori_Id == ConvertId);
                    db.tbl_Origins.DeleteObject(tbl_Origins);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PacketIntranet/Controllers/Products/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PacketIntranet.Models;
using PacketIntranet.Models.ProductModel;
using PacketIntranet.Helpers;
using System.Configuration;
using System.IO;

namespace PacketIntranet.Controllers.Products
{ 
    public class ProductManagerController : Controller
    {
        private MvcApplicationDBEntities db = new MvcApplicationDBEntities();

        //
        // GET: /ProductManager/

        public ViewResult Index()
        {
            ProductsModel model = new ProductsModel()
            {
                list_tbl_Product = db.tbl_Products.OrderByDescending(a=>a.Pro_Id).ToList(),
                list_tbl_Origin = db.tbl_Origins.ToList(),
                list_tbl_ProductType = db.tbl_ProductTypes.ToList(),
                list_tbl_Unit = db.tbl_Units.ToList()
            };
            return View(model);
        }

        //
        // GET: /ProductManager/Details/5

        public ViewResult Details(int id)
        {
            tbl_Products tbl_products = db.tbl_Products.Single(t => t.Pro_Id == id);
            return View(tbl_products);
        }

        public ActionResult Create()
        {
            string pathImage = ConfigurationManager.ConnectionStrings["pathImg_Product"].ToString(); // đường dẫn hình cần lưu
            ProductsModel model = new ProductsModel()
            {
                one_tbl_Product = new tbl_Products(),
                getPath = pathImage,
                list_tbl_Origin = db.tbl_Origins.ToList(),
                list_tbl_ProductType = db.tbl_ProductTypes.ToList(),
                list_tbl_Unit = db.tbl_Units.ToList()
            };
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ProductsModel tbl_Products, FormCollection Collection)
        {
            if (ModelState.IsValid)
            {
                int CheckInsert =Common.ParseInt(Collection.Get("Check_Insert_PrimaryKey"));
                if (CheckInsert == 1)
                {
                    tbl_Products.one_tbl_Product.ProType_Id = Common.ParseInt(Collection.Get("one_tbl_ProductType.ProType_Id"));
                    tbl_Products.one_tbl_Product.Ori_Id = Common.ParseInt(Collection.Get("one_tbl_Origin.Ori_Id"));
                    tbl_Products.one_tbl_Product.Unit_Id = Common.ParseInt(Collection.Get("one_tbl_Unit.Unit_Id"));
                }
                db.tbl_Products.AddObject(tbl_Products.one_tbl_Product);
                db.SaveChanges();


                for (int item = 0; item < Request.Files.Count; item++)
                {
                    try
                    {
                        string strImageName = "", strImageType = "";
                        // đếm số lượng file 
                        var imageFile = Request.Files[item];
                        strImageName = imageFile.FileName;
                        strImageType = strImageName.Substring(strImageName.LastIndexOf("."));
                        string NameFile = Convert.ToString(DateTime.Now.ToShortDateString()).Replace("/","-") + strImageType;
                        string pathStoredImage = ConfigurationManager.ConnectionStrings["pathImg_Product"].ToString(); // đường dẫn hình cần lưu

                        tbl_files NewFile = new tbl_files();
                        NewFile.Pro_Id = tbl_Products.one_tbl_Product.Pro_Id;
                        db.tbl_files.AddObject(NewFile);
                        db.SaveChanges();

                        var UpdateFile = db.tbl_files.Single(a => a.Fil_Id == NewFile.Fil_Id);
                        UpdateFile.Fil_Name = UpdateFile.Fil_Name + NewFile.Fil_Id + strImageType;
                        UpdateModel(UpdateFile);
                        db.SaveChanges();
                        Common.UploadFile(imageFile, pathStoredImage, UpdateFile.Fil_Name);

                       




                    }
                    catch
                    {
                        throw;
                    }
                }









                return RedirectToAction("Index");
            }

            return View(tbl_Products);
        }

        //
        // GET: /ProductTypesManager/Edit/5

        public ActionResult Edit(int id)
        {
               string pathImage = ConfigurationManager.ConnectionStrings["pathImg_Product"].ToString(); // đường dẫn hình cần lưu
            ProductsModel model = new ProductsModel()
            {
                getPath = pathImage,
                one_tbl_Product = db.tbl_Products.Single(t => t.Pro_Id == id),
                list_tbl_files = db.tbl_files.Where(a=>a.Pro_Id == id).ToList(),
                list_tbl_Origin = db.tbl_Origins.ToList(),
                list_tbl_ProductType = db.tbl_ProductTypes.ToList(),
                list_tbl_Unit = db.tbl_Units.ToList()
            };
            // tbl_Products tbl_Products = db.tbl_Products.Single(t => t.Ori_Id == id);
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ProductsModel tbl_Products, int id, FormCollection Collection)
        {
            if (ModelState.IsValid)
            {
                var Update_Products = db.tbl_Products.Single(a => a.Pro_Id == id);
                Update_Products.ProType_Id = tbl_Products.one_tbl_Product.ProType_Id;
                Update_Products.Ori_Id = tbl_Products.one_tbl_Product.Ori_Id;
                Update_Products.Unit_Id = tbl_Products.one_tbl_Product.Unit_Id;
                Update_Products.Pro_Name = tbl_Products.one_tbl_Product.Pro_Name;
                Update_Products.Pro_Images = tbl_Products.one_tbl_Product.Pro_Images;
                Update_Products.Pro_Price = tbl_Products.one_tbl_Product.Pro_Price;
                Update_Products.Pro_Warranty = tbl_Products.one_tbl_Product.Pro_Warranty;
                Update_Products.Descriptions = tbl_Products.one_tbl_Product.Descriptions;

                UpdateModel(Update_Products);
                db.SaveChanges();



                /////////////////////////////////////////////////////////////////////////////////////////////

                var GroupFile = db.tbl_files.Where(a => a.Pro_Id == id);

                var Deletename = Collection.Get("DelectImageProduct");

                ////// Delete Image ////////////////////////////////////////////////////
                if (Deletename != null)
                {
                    foreach (var iteem in Deletename.Split(','))
                    {
                        string Name = "";
                        Name = iteem;
                        DeleteImage(id, Name);

                    }
                }
                //kiểm tra số phần tử dc ADD hình vào thêm
                int NumberUpload = 0;
                foreach (string itemAddImage in Request.Files.AllKeys)
                {

                    if (itemAddImage == "UploadImage[]")
                    {
                        NumberUpload = NumberUpload + 1;
                    }
                }
                //// dem số file vừa add vào ////////////////
                for (int i = 0; i < NumberUpload; i++)
                {
                    #region
                    var file = Request.Files[i];
                    string strFileName = Path.GetFileName(file.FileName);
                    if (strFileName != "")
                    {

                        tbl_files tbl_file = new tbl_files();
                        tbl_file.Pro_Id = id;
                        db.tbl_files.AddObject(tbl_file);
                        db.SaveChanges();

                        string strImageName = "", strImageType = "";
                        var imageFile = Request.Files[i];
                        strImageName = imageFile.FileName;
                        strImageType = strImageName.Substring(strImageName.LastIndexOf("."));
                        string pathStoredImage = ConfigurationManager.ConnectionStrings["pathImg_Product"].ToString();

                        var UpdateNewFile = db.tbl_files.Single(a => a.Fil_Id == tbl_file.Fil_Id);
                        UpdateNewFile.Fil_Name = UpdateNewFile.Fil_Id + strImageType;
                        UpdateModel(UpdateNewFile);
                        db.SaveChanges();
                        Common.UploadFile(imageFile, pathStoredImage, UpdateNewFile.Fil_Name);

                        #region thumnails Images
                        //System.Drawing.Image image = System.Drawing.Image.FromStream(Request.Files[i].InputStream);
                        //string FilePath = Request.PhysicalApplicationPath + "Content\\RealImages\\";
                        //string LocalFile = "";
                        //int imgWidth = 252, imgHeight = 192;
                        //System.Drawing.Image thumb1 = image.GetThumbnailImage((int)imgWidth, (int)imgHeight, delegate() { return false; }, (IntPtr)0);
                        //LocalFile = FilePath + tbl_file.FileId + "_thumbnail" + strImageType;
                        //thumb1.Save(LocalFile);
                        #endregion


                    }

                    #endregion
                }
                ////////////end dem số file vừa add vào////////////////
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    #region
                    var file = Request.Files[i];
                    string strFileName = Path.GetFileName(file.FileName);


PacketIntranet/Controllers/Products/UnitManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PacketIntranet.Models;
using PacketIntranet.Models.ProductModel;

namespace PacketIntranet.Controllers
{ 
    public class UnitManagerController : Controller
    {
        private MvcApplicationDBEntities db = new MvcApplicationDBEntities();

        //
        // GET: /ProductTypesManager/

        public ViewResult Index()
        {
            UnitModel model = new UnitModel()
            {
                List_tbl_Units = db.tbl_Units.ToList(),
            };
            return View(model);
        }

        //
        // GET: /ProductTypesManager/Details/5

        public ViewResult Details(int id)
        {
            tbl_Units tbl_Units = db.tbl_Units.Single(t => t.Unit_Id == id);
            return View(tbl_Units);
        }

        //
        // GET: /ProductTypesManager/Create

        public ActionResult Create()
        {

            UnitModel model = new UnitModel()
            {
                One_tbl_Unit = new tbl_Units()
            };
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(UnitModel tbl_Units)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Units.AddObject(tbl_Units.One_tbl_Unit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Units);
        }

        //
        // GET: /ProductTypesManager/Edit/5

        public ActionResult Edit(int id)
        {
            UnitModel model = new UnitModel()
            {
                One_tbl_Unit = db.tbl_Units.Single(t => t.Unit_Id == id),
            };
            // tbl_Units tbl_Units = db.tbl_Units.Single(t => t.Unit_Id == id);
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(UnitModel tbl_Units, int id)
        {
            if (ModelState.IsValid)
            {
                var Update_Unit = db.tbl_Units.Single(a => a.Unit_Id == id);
                Update_Unit.Unit_Name = tbl_Units.One_tbl_Unit.Unit_Name;
                Update_Unit.Description = tbl_Units.One_tbl_Unit.Description;

                UpdateModel(Update_Unit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Units);
        }



        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(FormCollection Collection)
        {
            string All_IdProductType = Collection.Get("GetAll_Id");
            foreach (var item in All_IdProductType.Split(','))
            {

                if (item.ToString() != "000")
                {
                    int ConvertId = Convert.ToInt32(item);
                    tbl_Units tbl_Units = db.tbl_Units.Single(t => t.Unit_Id == ConvertId);
                    db.tbl_Units.DeleteObject(tbl_Units);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PacketIntranet/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title>Dashboard I Admin Panel</title>
	
	<link rel="stylesheet" href="../../Content/themeHTML/css/layout.css" type="text/css" media="screen" />
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->


	<script src="../../Content/themeHTML/js/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="../../Content/themeHTML/js/hideshow.js" type="text/javascript"></script>
	<script src="../../Content/themeHTML/js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="../../Content/themeHTML/js/jquery.equalHeight.js"></script>


    <script src="../../Scripts/jquery.MultiFile.js" type="text/javascript"></script>
	<script type="text/javascript">
	    $(document).ready(function () {
	        $(".tablesorter").tablesorter();
	    }
	);
	    $(document).ready(function () {

	        //When page loads...
	        $(".tab_content").hide(); //Hide all content
	        $("ul.tabs li:first").addClass("active").show(); //Activate first tab
	        $(".tab_content:first").show(); //Show first tab content

	        //On Click Event
	        $("ul.tabs li").click(function () {

	            $("ul.tabs li").removeClass("active"); //Remove any "active" class
	            $(this).addClass("active"); //Add "active" class to selected tab
	            $(".tab_content").hide(); //Hide all tab content

	            var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
	            $(activeTab).fadeIn(); //Fade in the active ID content
	            return false;
	        });

	    });
    </script>
    <script type="text/javascript">
        $(function () {
            $('.column').equalHeight();
        });
</script>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script src="../../Scripts/tinymce/jscripts/tiny_mce/tiny_mce.js" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options 
        mode: "textareas",
        theme: "advanced",
        plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell," +
"inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste," +
"directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template," +
"wordcount,advlist,autosave",
        setup: function (ed) {
            ed.onKeyPress.add(
function (ed, evt) {
}
);
        },
        // Theme options 
        theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|," +
"justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect," +
"fontselect,fontsizeselect",
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|," +
"bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor," +
"image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|," +
"charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|," +
"styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking," +
"template,pagebreak,restoredraft",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,
        // Example content CSS (should be your site CSS) 
        content_css: "css/content.css",
        // Drop lists for link/image/media/template dialogs 
        template_external_list_url: "lists/template_list.js",
        external_link_list_url: "lists/link_list.js",
        external_image_list_url: "lists/image_list.js",
        media_external_list_url: "lists/media_list.js",
        // Style formats 
        style_formats: [
{ title: 'Bold text', inline: 'b' },
{ title: 'Red text', inline: 'span', styles: { color: '#ff0000'} },
{ title: 'Red header', block: 'h1', styles: { color: '#ff0000'} },
{ title: 'Example 1', inline: 'span', classes: 'example1' },
{ title: 'Example 2', inline: 'span', classes: 'example2' },
{ title: 'Table styles' },
{ title: 'Table row 1', selector: 'tr', classes: 'tablerow1' }
],
        // Replace values for the template plugin 
        template_replace_values: {
            username: "Some User",
            staffid: "991234"
        }
    }); 
    </script>




</head>


<body>

	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">Website Admin</a></h1>
			<h2 class="section_title">Dashboard</h2><div class="btn_view_site"><a href="http://www.medialoot.com">View Site</a></div>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<section id="secondary_bar">
		<div class="user">
			<p>John Doe (<a href="#">3 Messages</a>)</p>
			<!-- <a class="logout_user" href="#" title="Logout">Logout</a> -->
		</div>
		<div class="breadcrumbs_container">
			<article class="breadcrumbs"><a href="index.html">Website Admin</a> <div class="breadcrumb_divider"></div> <a class="current">Dashboard</a></article>
		</div>
	</section><!-- end of secondary bar -->
	
	<aside id="sidebar" class="column">
		<form class="quick_search">
			<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
		</form>
		<hr/>
		<h3>Product Type Manager</h3>    
		<ul class="toggle">
        <li class="icn_categories"><a href="@Url.Action("Index", "ProductTypesManager")">Index ProductType</a></li>
			<li class="icn_new_article"><a href="@Url.Action("Create", "ProductTypesManager")">New ProductType</a></li>
			
		
		  <h3>Origin Manager</h3>    
		<ul class="toggle">
        <li class="icn_categories"><a href="@Url.Action("Index", "OriginManager")">Index Origin</a></li>
			<li class="icn_new_article"><a href="@Url.Action("Create", "OriginManager")">New Origin</a></li>
			
		</ul>
        </ul>
		  <h3>Unit Manager</h3>    
		<ul class="toggle">
        <li class="icn_categories"><a href="@Url.Action("Index", "UnitManager")">Index Unit</a></li>
			<li class="icn_new_article"><a href="@Url.Action("Create", "UnitManager")">New Unit</a></li>
			
		</ul>
		</ul>
        <h3>Product Manager</h3>    
		<ul class="toggle">
        <li class="icn_categories"><a href="@Url.Action("Index", "ProductManager")">Index Product</a></li>
			<li class="icn_new_article"><a href="@Url.Action("Create", "ProductManager")">New Product</a></li>
			
		</ul>
		</ul>
        <h3>Articles Manager</h3>    
		<ul class="toggle">
        <li class="icn_categories"><a href="@Url.Action("Index", "ArticlesManager")">Index Articles</a></li>
			<li class="icn_new_article"><a href="@Url.Action("Create", "ArticlesManager")">New Articles</a></li>
			
		</ul>
		<footer>
			<hr />
			<p><strong>Copyright &copy; 2011 Website Admin</strong></p>
			<p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
		</footer>
	</aside><!-- end of sidebar -->
	
	<section id="main" class="column">
		
		@RenderBody()
	</section>


</body>

</html>