PacketIntranet/Controllers/Products/ProductTypesManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PacketIntranet.Models;
using PacketIntranet.Models.ProductModel;

namespace PacketIntranet.Controllers
{ 
    public class ProductTypesManagerController : Controller
    {
        private MvcApplicationDBEntities db = new MvcApplicationDBEntities();

        //
        // GET: /ProductTypesManager/

        public ViewResult Index()
        {
            ProductTypeModel model = new ProductTypeModel()
            {
                List_tbl_ProductType = db.tbl_ProductTypes.ToList(),
            };
            return View(model);
        }

        //
        // GET: /ProductTypesManager/Details/5

        public ViewResult Details(int id)
        {
            tbl_ProductTypes tbl_producttypes = db.tbl_ProductTypes.Single(t => t.ProType_Id == id);
            return View(tbl_producttypes);
        }

        //
        // GET: /ProductTypesManager/Create

        public ActionResult Create()
        {
           
            ProductTypeModel model = new ProductTypeModel()
            {
                One_tbl_ProductType = new tbl_ProductTypes()
            };
            return View(model);
        } 

        //
        // POST: /ProductTypesManager/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ProductTypeModel tbl_producttypes)
        {
            if (ModelState.IsValid)
            {
                db.tbl_ProductTypes.AddObject(tbl_producttypes.One_tbl_ProductType);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tbl_producttypes);
        }
        
        //
        // GET: /ProductTypesManager/Edit/5
 
        public ActionResult Edit(int id)
        {
            ProductTypeModel model = new ProductTypeModel()
            {
                One_tbl_ProductType = db.tbl_ProductTypes.Single(t => t.ProType_Id == id),
            };
           // tbl_ProductTypes tbl_producttypes = db.tbl_ProductTypes.Single(t => t.ProType_Id == id);
            return View(model);
        }

        //
        // POST: /ProductTypesManager/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ProductTypeModel tbl_producttypes, int id)
        {
            if (ModelState.IsValid)
            {
                var Update_ProductType = db.tbl_ProductTypes.Single(a => a.ProType_Id == id);
                Update_ProductType.ProType_Name = tbl_producttypes.One_tbl_ProductType.ProType_Name;
                Update_ProductType.Descriptions = tbl_producttypes.One_tbl_ProductType.Descriptions;

                UpdateModel(Update_ProductType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_producttypes);
        }

       

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(FormCollection Collection)
        {
            string All_IdProductType = Collection.Get("GetAll_Id");
            foreach (var item in All_IdProductType.Split(','))
            {
                
                if (item.ToString() != "000")
                {
                    int ConvertId = Convert.ToInt32(item);
                    tbl_ProductTypes tbl_producttypes = db.tbl_ProductTypes.Single(t => t.ProType_Id == ConvertId);
                    db.tbl_ProductTypes.DeleteObject(tbl_producttypes);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PacketIntranet/Views/ProductTypesManager/Create.cshtml
@model PacketIntranet.Models.ProductModel.ProductTypeModel

@{
    ViewBag.Title = "Create";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">New ProductType Manager</h3></header>
		<div class="tab_container">

          @Html.EditorFor(model => model.One_tbl_ProductType)


         <footer>
				<div class="submit_link">
                	 @Html.ActionLink("Back to List", "Index")
					<input type="submit" value="Add ProductType" class="alt_btn">
				
				</div>
			</footer>
        </div>
</article>
}

PacketIntranet/Views/ProductTypesManager/Delete.cshtml
@model PacketIntranet.Models.ProductModel.ProductTypeModel

@{
    ViewBag.Title = "Delete";
}

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>tbl_ProductTypes</legend>

    <div class="display-label">ProType_Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProType_Name)
    </div>

    <div class="display-label">Descriptions</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descriptions)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
*@

<article class="module width_full">
			<header><h3>ARE YOU SURE YOU WANT TO DELETE ?</h3>
            </header>
				<div class="module_content">
                <table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr>  
    				<th>ProductType</th> 
                    <th>Delete</th> 
				</tr> 
			</thead> 
			<tbody> 
            @{string All_Id = "";}
            @foreach (var item in Model.List_tbl_ProductType)
            {
                All_Id = All_Id + item.ProType_Id + ",";
                
				<tr> 
   					
    				<td>ProductType :  <span style="color:Red">@item.ProType_Name</span></td> 
                    <td><input type="checkbox" checked="checked" name="deleteAll" value="@item.ProType_Id"></td> 
                  
    				
				</tr> 
            }
			</tbody> 
			</table>






         
                     <footer>
				<div class="submit_link">
                	 @Html.ActionLink("Back to List", "Index")
				
				</div>
			</footer>
				</div>
		</article><!-- end of styles article -->

PacketIntranet/Views/ProductTypesManager/DeleteALL Index.cshtml
@model PacketIntranet.Models.ProductModel.ProductTypeModel

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('.FormMes_delete').hide();
        $('.Checkvalue').hide();

        $('#ShowMesg').click(function () {

            if ($(".Check").is(':checked') == true) {
                $('.FormMes_delete').show();
                return false;
            } else {
                $('.Checkvalue').show();
                return false;
            }

        });

        $('#hiden').click(function () {
            $('.FormMes_delete').hide();
        });
        $('#Close').click(function () {
            $('.Checkvalue').hide();
        });


    });
    function DoneCallController() {
        return false;
    };
   
    </script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $('#chkAll').click(function () {
                $("input[type=checkbox]").each(function () {
                    if (this.checked == true) {
                        $("input[type=checkbox]").attr('checked', 'checked');
                    }
                    else {
                        $("input[type=checkbox]").attr('checked', false);
                    }
                });
            });
        });
</script>

 <div class="Checkvalue">
 <div class="please">
        <div class="title"><p>Please select least 1 record !</p></div>
                        <div class="button">
                            <input type="submit" id="Close" value="Close"/>
                        </div>

 </div>
 </div>


<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Product Type Manager</h3>
		<ul class="tabs">
   			<li><a href="#tab1">Index</a></li>
    		<li><a href="#tab2">New</a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">
			 @using (Html.BeginForm("Delete", "ProductTypesManager"))
             {
            <div class="FormMes_delete">
                <div class="FormContent">
                    <div class="title"><p>Are you sure you want to delete this?</p></div>
                        <div class="button">
                            <input type="submit" id="Check_ID" onclick="return CallController();"/>
                            <input type="submit" id="hiden" value="Cancel" onclick="return DoneCallController();"/>
                        </div>
                </div>
            </div>
        
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th class="remove"><input type="checkbox" id="chkAll" /></th> 
    				<th class="sort">ProductsType</th> 
                   @* <th>Descriptions</th> *@
    				<th>Actions</th> 
				</tr> 
			</thead> 
			<tbody> 
            @{string All_Id = "";}
            @foreach (var item in Model.List_tbl_ProductType)
            {
                All_Id = All_Id + item.ProType_Id + ",";
                
				<tr> 
   					<td><input type="checkbox" value="@item.ProType_Id" name="GetAll_Id" class="Check" ></td> 
    				<td> <a href="@Url.Action("Details", "ProductTypesManager", new { @id = item.ProType_Id })">@item.ProType_Name</a></td> 
                   @* <td>@Html.Raw(item.Descriptions)</td> *@
    				<td>
                     <a href="@Url.Action("Edit", "ProductTypesManager", new { @id = item.ProType_Id })"><input type="image" src="../../Content/themeHTML/images/icn_edit.png" title="Edit"></a>   
                        
                   </td> 
				</tr> 
            }
           
			</tbody> 
			</table>
             <footer>
				<div class="submit_link">
					<input type="submit" value="Delete" class="alt_btn"  id="ShowMesg">
				</div>
			</footer>
             }
			</div><!-- end of #tab1 -->
			
			<div id="tab2" class="tab_content">
            @using (Html.BeginForm("Create", "ProductTypesManager"))
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <label>ProductType</label>
                    @Html.EditorFor(model => model.One_tbl_ProductType.ProType_Name)
		        </fieldset>
                 <fieldset>
                    <label>Descriptions</label>
                    @Html.TextAreaFor(a => a.One_tbl_ProductType.Descriptions, new { rows = 5 })
		        </fieldset>

                <footer>
				<div class="submit_link">
					<input type="submit" value="Add ProductType" class="alt_btn">
					<input type="submit" value="Reset">
				</div>
			</footer>
            }
			</div><!-- end of #tab2 -->
			
		</div><!-- end of .tab_container -->
		
		</article><!-- end of content manager article -->

PacketIntranet/Views/ProductTypesManager/Details.cshtml
@model PacketIntranet.Models.tbl_ProductTypes

@{
    ViewBag.Title = "Details";
}

<article class="module width_full">
			<header><h3>Detail ProductType : <span style="color:Red">@Model.ProType_Name</span></h3></header>
				<div class="module_content">
					@Html.Raw(Model.Descriptions)

                     <footer>
				<div class="submit_link">
                	 @Html.ActionLink("Back to List", "Index")
				
				</div>
			</footer>
				</div>
		</article><!-- end of styles article -->

PacketIntranet/Views/ProductTypesManager/Edit.cshtml
@model PacketIntranet.Models.ProductModel.ProductTypeModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Edit ProductType Manager</h3></header>
		<div class="tab_container">

          @Html.EditorFor(model => model.One_tbl_ProductType)


         <footer>
				<div class="submit_link">
                	 @Html.ActionLink("Back to List", "Index")
					<input type="submit" value="Save ProductType" class="alt_btn">
				
				</div>
			</footer>
        </div>
</article>
}

PacketIntranet/Views/ProductTypesManager/Index.cshtml
<!-------------------------------------->
@model PacketIntranet.Models.ProductModel.ProductTypeModel

@{
    ViewBag.Title = "Index";
}



<script type="text/javascript">
    $(document).ready(function () {
        $('.FormMes_delete').hide();
        $('.Checkvalue').hide();

        $('#ShowMesg').click(function () {
            if ($(".Check").is(':checked') == true) {
                $('.FormMes_delete').show();
                return false;
            } else {
                $('.Checkvalue').show();
                return false;
            }
        });


        $('#Check_ID').click(function () {
            var Check_val = [];
            $(':checkbox:checked').each(function (i) {
                Check_val[i] = $(this).val();
            });
            document.getElementById('hiden_ID').value = Check_val;
        });
        $('#hiden').click(function () {
            $('.FormMes_delete').hide();
        });
        $('#Close').click(function () {
            $('.Checkvalue').hide();
        });
    });
    function DoneCallController() {
        return false;
    };
   
    </script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $('#chkAll').click(function () {
                $("input[type=checkbox]").each(function () {
                    if (this.checked == true) {
                        $("input[type=checkbox]").attr('checked', 'checked');
                    }
                });


            });
            $('.Check').click(function () {
                // $('#chkAll').attr('checked', 'checked')
                $('#chkAll').removeAttr('checked')
            });
        });



        function SetValueForCheckbox(thisvalue) {
            var addvalue = thisvalue.value;
            var hiddenValue = document.getElementById('hiden_ID').value;

            if (thisvalue.checked == true) {
                document.getElementById('hiden_ID').value = document.getElementById('hiden_ID').value + "," + addvalue;
            }
            else {
                document.getElementById('hiden_ID').value = document.getElementById('hiden_ID').value.replace("," + addvalue, "");
            }
        }

</script>
 <div class="Checkvalue">
 <div class="please">
        <div class="title"><p>Please select least at 1 record !</p></div>
                        <div class="button">
                            <input type="submit" id="Close" value="Close"/>
                        </div>

 </div>
 </div>

 			 @using (Html.BeginForm("Delete", "ProductTypesManager", FormMethod.Post, new { id = "changeAction-form" }))
    {
        <input type="hidden" id="hiden_ID" name="GetAll_Id" />
            <div class="FormMes_delete">
                <div class="FormContent">
                    <div class="title"><p>Are you sure you want to delete this?</p></div>
                        <div class="button">
                            <input type="submit" id="Check_ID" onclick="return CallController();"/>
                            <input type="submit" id="hiden" value="Cancel" onclick="return DoneCallController();"/>
                        </div>
                </div>
            </div>
    }

<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Product Type Manager</h3>
		<ul class="tabs">
   			<li><a href="#tab1">Index</a></li>
    		<li><a href="#tab2">New</a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">

			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th class="remove"><input type="checkbox" id="chkAll" value="000" /></th> 
    				<th class="sort">ProductsType</th> 
    				<th>Actions</th> 
				</tr> 
			</thead> 
			<tbody> 
            @{string All_Id = "";}
            @foreach (var item in Model.List_tbl_ProductType)
            {
                All_Id = All_Id + item.ProType_Id + ",";
                
				<tr> 
   					<td><input type="checkbox" value="@item.ProType_Id"  class="Check" onclick="SetValueForCheckbox(this);" ></td> 
    				<td> <a href="@Url.Action("Details", "ProductTypesManager", new { @id = item.ProType_Id })">@item.ProType_Name</a></td> 
    				<td><a href="@Url.Action("Edit", "ProductTypesManager", new { @id = item.ProType_Id })"><input type="image" src="../../Content/themeHTML/images/icn_edit.png" title="Edit"></a>   
                        
                   </td> 
				</tr> 
            }
           
			</tbody> 
			</table>
             <footer>
				<div class="submit_link">
					<input type="submit" value="Delete" class="alt_btn"  id="ShowMesg">
				</div>
			</footer>
    
			</div><!-- end of #tab1 -->
			
			<div id="tab2" class="tab_content">
            @using (Html.BeginForm("Create", "ProductTypesManager"))
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <label>ProductType</label>
                    @Html.EditorFor(model => model.One_tbl_ProductType.ProType_Name)
		        </fieldset>
                 <fieldset>
                    <label>Descriptions</label>
                    @Html.TextAreaFor(a => a.One_tbl_ProductType.Descriptions, new { rows = 5 })
		        </fieldset>

                <footer>
				<div class="submit_link">
					<input type="submit" value="Add ProductType" class="alt_btn">
					<input type="submit" value="Reset">
				</div>
			</footer>
            }
			</div><!-- end of #tab2 -->
			
		</div><!-- end of .tab_container -->
		
		</article><!-- end of content manager article -->