PacketIntranet/Controllers/Articles/ArticlesManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PacketIntranet.Models;
using PacketIntranet.Models.ArticleModel;
using PacketIntranet.Helpers;
using System.Configuration;

namespace PacketIntranet.Controllers.Articles
{ 
    public class ArticlesManagerController : Controller
    {
        private MvcApplicationDBEntities db = new MvcApplicationDBEntities();

        //
        // GET: /ArticlesManager/

        public ViewResult Index()
        {
            var listCategory = db.tbl_Articles.Where(a => a.Type == 1);
            ArticleModel model = new ArticleModel()
            {
                List_tbl_Articles = db.tbl_Articles.ToList(),
                list_Categorys = listCategory.ToList()
            };
            return View(model);
        }

        //
        // GET: /ArticlesManager/Details/5

        public ViewResult Details(int id)
        {
            tbl_Articles tbl_articles = db.tbl_Articles.Single(t => t.ArticleId == id);
            return View(tbl_articles);
        }

        //
        // GET: /ArticlesManager/Create

        public ActionResult Create()
        {
            var listCategory = db.tbl_Articles.Where(a => a.Type == 1);
            ArticleModel model = new ArticleModel()
            {
                List_tbl_Articles = db.tbl_Articles.ToList(),
                list_Categorys = db.tbl_Articles.Where(a => a.Type == 1).ToList(),
                one_tbl_Articles = new tbl_Articles()
            };
            return View(model);
        } 

        //
        // POST: /ArticlesManager/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ArticleModel tbl_articles, FormCollection Collection)
        {

            //if (ModelState.IsValid)
            //{
                int CheckInsert = Common.ParseInt(Collection.Get("Check_Insert_PrimaryKey"));
                if (CheckInsert == 1)
                {
                    //tbl_Products.one_tbl_Product.ProType_Id = Common.ParseInt(Collection.Get("one_tbl_ProductType.ProType_Id"));
                    //tbl_Products.one_tbl_Product.Ori_Id = Common.ParseInt(Collection.Get("one_tbl_Origin.Ori_Id"));
                    //tbl_Products.one_tbl_Product.Unit_Id = Common.ParseInt(Collection.Get("one_tbl_Unit.Unit_Id"));
                   // tbl_articles.one_tbl_Articles.
                }
                tbl_articles.one_tbl_Articles.PostDate = DateTime.Now;
                tbl_articles.one_tbl_Articles.Type = Common.ParseInt(Collection.Get("Type"));
                
                db.tbl_Articles.AddObject(tbl_articles.one_tbl_Articles);
                db.SaveChanges();

                if (Request.Files.Count > 0)
                {
                    for (int item = 0; item < Request.Files.Count; item++)
                    {
                        try
                        {
                            string strImageName = "", strImageType = "";
                            // đếm số lượng file 
                            var imageFile = Request.Files[item];
                            strImageName = imageFile.FileName;
                            strImageType = strImageName.Substring(strImageName.LastIndexOf("."));
                            string pathStoredImage = ConfigurationManager.ConnectionStrings["pathImg_Article"].ToString(); // đường dẫn hình cần lưu
                            var updateFeatureImage = db.tbl_Articles.Single(a => a.ArticleId == tbl_articles.one_tbl_Articles.ArticleId).ArticleId;
                            string fileName = Common.ParseString(updateFeatureImage) + strImageType;

                            Common.UploadFile(imageFile, pathStoredImage, fileName);
                        }
                        catch
                        {
                        }
                    }
                }
                return RedirectToAction("Index");
               
            //}
            //return View(tbl_articles);
        }
        
        //
        // GET: /ArticlesManager/Edit/5
 
        public ActionResult Edit(int id)
        {
            tbl_Articles tbl_articles = db.tbl_Articles.Single(t => t.ArticleId == id);
            return View(tbl_articles);
        }

        //
        // POST: /ArticlesManager/Edit/5

        [HttpPost]
        public ActionResult Edit(tbl_Articles tbl_articles)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Articles.Attach(tbl_articles);
                db.ObjectStateManager.ChangeObjectState(tbl_articles, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_articles);
        }

        //
        // GET: /ArticlesManager/Delete/5
 
        public ActionResult Delete(int id)
        {
            tbl_Articles tbl_articles = db.tbl_Articles.Single(t => t.ArticleId == id);
            return View(tbl_articles);
        }

        //
        // POST: /ArticlesManager/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            tbl_Articles tbl_articles = db.tbl_Articles.Single(t => t.ArticleId == id);
            db.tbl_Articles.DeleteObject(tbl_articles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PacketIntranet/Views/ArticlesManager/Create.cshtml
@model PacketIntranet.Models.ArticleModel.ArticleModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "ArticlesManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Add</h3></header>
		<div class="tab_container">

          @Html.EditorFor(model => model.one_tbl_Articles, new { ViewArticleCategory = Model.list_Categorys })


         <footer>
				<div class="submit_link">
                	 @Html.ActionLink("Back to List", "Index")
					<input type="submit" value="Add" class="alt_btn">
				
				</div>
			</footer>
        </div>
</article>
}

PacketIntranet/Views/ArticlesManager/Delete.cshtml
@model PacketIntranet.Models.tbl_Articles

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>tbl_Articles</legend>

    <div class="display-label">Art_Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Title)
    </div>

    <div class="display-label">Art_Type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Type)
    </div>

    <div class="display-label">PostDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostDate)
    </div>

    <div class="display-label">FeatureImage</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FeatureImage)
    </div>

    <div class="display-label">Art_ReadMore</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_ReadMore)
    </div>

    <div class="display-label">Art_Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Content)
    </div>

    <div class="display-label">Art_Meta</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Meta)
    </div>

    <div class="display-label">Status</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">Author</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PacketIntranet/Views/ArticlesManager/Details.cshtml
@model PacketIntranet.Models.tbl_Articles

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>tbl_Articles</legend>

    <div class="display-label">Art_Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Title)
    </div>

    <div class="display-label">Art_Type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Type)
    </div>

    <div class="display-label">PostDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostDate)
    </div>

    <div class="display-label">FeatureImage</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FeatureImage)
    </div>

    <div class="display-label">Art_ReadMore</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_ReadMore)
    </div>

    <div class="display-label">Art_Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Content)
    </div>

    <div class="display-label">Art_Meta</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Art_Meta)
    </div>

    <div class="display-label">Status</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">Author</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Art_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PacketIntranet/Views/ArticlesManager/Edit.cshtml
@model PacketIntranet.Models.tbl_Articles

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>tbl_Articles</legend>

        @Html.HiddenFor(model => model.Art_Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Art_Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Art_Title)
            @Html.ValidationMessageFor(model => model.Art_Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Art_Type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Art_Type)
            @Html.ValidationMessageFor(model => model.Art_Type)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PostDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostDate)
            @Html.ValidationMessageFor(model => model.PostDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FeatureImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FeatureImage)
            @Html.ValidationMessageFor(model => model.FeatureImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Art_ReadMore)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Art_ReadMore)
            @Html.ValidationMessageFor(model => model.Art_ReadMore)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Art_Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Art_Content)
            @Html.ValidationMessageFor(model => model.Art_Content)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Art_Meta)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Art_Meta)
            @Html.ValidationMessageFor(model => model.Art_Meta)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PacketIntranet/Views/ArticlesManager/Index.cshtml
@model PacketIntranet.Models.ArticleModel.ArticleModel

@{
    ViewBag.Title = "Index";
}



<script type="text/javascript">
    $(document).ready(function () {
        $('.FormMes_delete').hide();
        $('.Checkvalue').hide();

        $('#ShowMesg').click(function () {
            if ($(".Check").is(':checked') == true) {
                $('.FormMes_delete').show();
                return false;
            } else {
                $('.Checkvalue').show();
                return false;
            }
        });


        $('#Check_ID').click(function () {
            var Check_val = [];
            $(':checkbox:checked').each(function (i) {
                Check_val[i] = $(this).val();
            });
            document.getElementById('hiden_ID').value = Check_val;
        });
        $('#hiden').click(function () {
            $('.FormMes_delete').hide();
        });
        $('#Close').click(function () {
            $('.Checkvalue').hide();
        });
    });
    function DoneCallController() {
        return false;
    };
   
    </script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $('#chkAll').click(function () {
                $("input[type=checkbox]").each(function () {
                    if (this.checked == true) {
                        $("input[type=checkbox]").attr('checked', 'checked');
                    }
                });


            });
            $('.Check').click(function () {
                // $('#chkAll').attr('checked', 'checked')
                $('#chkAll').removeAttr('checked')
            });
        });



        function SetValueForCheckbox(thisvalue) {
            var addvalue = thisvalue.value;
            var hiddenValue = document.getElementById('hiden_ID').value;

            if (thisvalue.checked == true) {
                document.getElementById('hiden_ID').value = document.getElementById('hiden_ID').value + "," + addvalue;
            }
            else {
                document.getElementById('hiden_ID').value = document.getElementById('hiden_ID').value.replace("," + addvalue, "");
            }
        }

</script>

 <div class="Checkvalue">
 <div class="please">
        <div class="title"><p>Please select least 1 record !</p></div>
                        <div class="button">
                            <input type="submit" id="Close" value="Close"/>
                        </div>

 </div>
 </div>

 	@using (Html.BeginForm("Delete", "ArticlesManager", FormMethod.Post, new { id = "changeAction-form" }))
    {
        <input type="hidden" id="hiden_ID" name="GetAll_Id" />
            <div class="FormMes_delete">
                <div class="FormContent">
                    <div class="title"><p>Are you sure you want to delete this?</p></div>
                        <div class="button">
                            <input type="submit" id="Check_ID" onclick="return CallController();"/>
                            <input type="submit" id="hiden" value="Cancel" onclick="return DoneCallController();"/>
                        </div>
                </div>
            </div>
    }

<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Product Type Manager</h3>
		<ul class="tabs">
   			<li><a href="#tab1">Index</a></li>
    		<li><a href="#tab2">New</a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">

			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th class="remove"><input type="checkbox" id="chkAll" value="000" /></th> 
    				<th class="sort">Title</th> 
                    <th class="sort">Type</th> 
                    <th class="sort">Post Date</th> 
                    <th class="sort">Images</th> 
                    <th class="sort">Status</th> 
    				<th>Actions</th> 
				</tr> 
			</thead> 
			<tbody> 
            @{string All_Id = "";}
            @foreach (var item in Model.List_tbl_Articles)
            {
                
				<tr> 
   					<td><input type="checkbox" value="@item.ArticleId"  class="Check" onclick="SetValueForCheckbox(this);" ></td> 
    				<td> <a href="@Url.Action("Details", "ArticlesManager", new { @id = item.ArticleId })">@item.Title</a></td> 
                    <td> @item.Type</td>
                    <td> @item.PostDate</td>
                    <td> @item.FeatureImage</td>
                    <td> @item.Status</td>
    				<td><a href="@Url.Action("Edit", "ArticlesManager", new { @id = item.ArticleId })"><input type="image" src="../../Content/themeHTML/images/icn_edit.png" title="Edit"></a>   
                        
                   </td> 
				</tr> 
            }
           
			</tbody> 
			</table>
             <footer>
				<div class="submit_link">
					<input type="submit" value="Delete" class="alt_btn"  id="ShowMesg">
				</div>
			</footer>
    
			</div><!-- end of #tab1 -->
			
			<div id="tab2" class="tab_content">
            @using (Html.BeginForm("Create", "ArticlesManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="hidden" name="Check_Insert_PrimaryKey" value="1" />
                
               @* @Html.ValidationSummary(true)*@
                <fieldset >
                    <label>Title</label>
                        @Html.TextBoxFor(a => a.one_tbl_Articles.Title)
		        </fieldset>
                
                 <fieldset style="width:48%; float:left;">
                    <label>Article Type</label>

                      <input type="radio" id="chil" value="0"name="Type" checked="checked"  onclick = "document.getElementById('one_tbl_Articles_ArticleId').disabled=(this.unchecked)" />Article 
                    
                      <input type="radio" id="parent" value="1" name="Type" onclick ="document.getElementById('one_tbl_Articles_ArticleId').disabled=(this.checked)" /> Category
                          
		        </fieldset>
                
                 <fieldset style="width:48%; float:right;">

                            <label style="width:100px">Parent Article</label>
                            
                               @Html.DropDownListFor(model => model.one_tbl_Articles.ArticleId, new SelectList(Model.list_Categorys as System.Collections.IEnumerable, "ArticleId", "Title"), "-- Select Parent --", new {@style="width:60%"  })
						</fieldset>
                
                <fieldset>
							<label>Feature Image</label>
							<input type="file" name="FeatureImage1" />
						</fieldset>
                
                 <fieldset>
                    <label>Read More</label>
                        @Html.TextAreaFor(a => a.one_tbl_Articles.ReadMore, new { rows = 5 })
		        </fieldset>
                
                 <fieldset>
                    <label>Content</label>
                        @Html.TextAreaFor(a => a.one_tbl_Articles.Content, new { rows = 5 })
		        </fieldset>
               
                

                <footer>
				<div class="submit_link">
					<input type="submit" value="Add" class="alt_btn">
					<input type="button" value="Reset">
				</div>
			</footer>
            }
			</div><!-- end of #tab2 -->
			
		</div><!-- end of .tab_container -->
		
		</article><!-- end of content manager article -->